### ISSUE TITLE
Figure out what to do about weight units

### ISSUE THREAD

**Issue by cfilipov** [cfilipov/MuscleBook#10]
Right now weight values are unit-less, which is ok as long as you are always logging lbs or always logging kg etc.. Need to figure out the cleanest way to support logging different units. One option is to always save to the db in kg and localize on display. but it might be useful to log the units if someone was using kg plates for example.

**Comment by JonathanGuberman** [comment]
As someone who usually has to use lbs plates but prefers to think in kgs, I'm definitely hoping for this feature. I'm not sure I understand your proposed use-case for logging units; if it's easy to change the entry units and display units, then why does it matter what type of plates someone is using?

**Comment by cfilipov** [comment]
Kg plates vs lbs plates come in different denominations. Sure, mass is mass, but when switching between plates you will be increasing mass at different increments and lifting different numbers. It might effect your performance in some way if you have always lifted lbs and then used kg plates one day. It would be useful to log this fact so that when you are looking back at your data you can say "hey, I didn't do so well that day because I switched to kg plates and wasn't used to it". I agree this might just be a moot point. But I raised this issue to get feedback on if this would be useful.

For what it's worth, a friend of mine went to a gym where they only had kg plates. They calculated how much they should lift and got as close as they could, but it still threw them off because they were used to adding 5-10lbs at a time. It may have just been psychological, but it effected performance so it's worth logging. 

Another option, people have asked for a "notes" field. This may be a good use case for that since this isn't something that provides any meaningful calculation, but it more informational to the user which is what notes would be good for.

**Comment by cfilipov** [comment]
One more reason for having a unit field in the DB. Deciding on metric vs imperial globally would be somewhat restrictive, in that all data is either kg or lbs. But if you spend enough time using both it will get annoying to log. Let's say you choose lbs, and you have done a year logging data using lbs. Then you go visit your buddy in europe for six months and train with them while you are there. For those six months you would be entering your weight values as "330.693" (lbs) instead of the much easier to read and understand "150" (lbs). Sure the app can help by doing the conversion for you at the time of entry. But I think the more useful case would be to say that this set is metric, so then the whole data entry screen will show you your PRs in metric units and make entry (and deciding what to lift) easier.

The more I think about it, the more I think it would be useful to have a unit column.

**Comment by JonathanGuberman** [comment]
Re: performance with kg vs. lbs plates: I suppose it could be a factor because of the different increments and numbers, but even if you don't explicitly record what style plates you are using ("on day one I went up in 10lbs increments, and on day 2 I went up in 11lbs increments; I must've been using kg plates on day 2!"). I agree that a notes field would also be useful for this (and other things!).

Re: restrictiveness of a global setting. I strongly agree that you should be able to change units at entry time. At my old gym there are both kg and lbs plates, and it happened sometimes that your preferred plates are in use, so you have to use to the other plates. Frankly, I'd also love it if it were very easy to toggle the display units without going into preferences, like on http://weightxreps.net/.

That said, I'm still not convinced that the change needs to be recorded in the DB. Maybe it's just my previous experience, but I'm uncomfortable with two entries in the same column not being directly comparable. If you want to do anything with that information (e.g. graph weight vs. time), you'd need to convert every data point, rather than just converting the scale at display time.

It seems to me that the biggest advantage to storing the units would be if you want to show a list with mixed units, based on the unit of entry. E.g.:

| Sets | Reps | Weight |
| --- | --- | --- |
| 3 | 5 | 100kg |
| 3 | 5 | 230lbs |
| 3 | 5 | 110kg |

But personally, I'd never be interested in seeing that. I'd rather see:

| Sets | Reps | Weight |
| --- | --- | --- |
| 3 | 5 | 100kg |
| 3 | 5 | 104.32kg |
| 3 | 5 | 110kg |

With an easy toggle to make it:

| Sets | Reps | Weight |
| --- | --- | --- |
| 3 | 5 | 220.46lbs |
| 3 | 5 | 230lbs |
| 3 | 5 | 242.51lbs |

Even in that case, I'd suggest storing the entry units, but still storing the data in the DB in a canonical unit, so you can do things like graphing and sorting without having to convert every entry.

**Comment by cfilipov** [comment]
I agree with all your points. 

I want to store the unit type as a column in the workset table (so every set is associated with lbs or kg), but the weight values themselves should be stored in the canonical units (kg most likely). 

One very strong reason for not mxing lbs and kg in the database itself is because of the way certain calculations are looked up. The most interesting calculations like %1RM, %e1RM etc.. are all based on all the data before the current workout, this would be pretty expensive to always query everything up to the current point and calculate (especially when I need daily summaries like on the main screen), so I have columns that caches these calculated values so it's just a matter of a simple lookup. Mixing lbs and kg would mean I would have to first convert units on each row because the columns wouldn't be directly comparable (or store even more cached values). I think i've done a pretty good job at keeping query performance fast and I'd like to keep it fast (in fact, it's all done on the main thread right now!).

I also agree that mixing units in the workout summary screen has little value (if you haven't seen this screen yet, it's kinda of hidden, tapping on the punchcard graph and selecting a day will display the workout summary).

Finally, I fully support the idea of selecting the unit in the [data entry screen](https://github.com/cfilipov/MuscleBook/blob/f655e422c172ef9c8e0ee2248b8bb90b74b1d7a8/Screenshots/AddDataPoint.png). Similarly, when navigating the view the details of a previously-entered set, the units should be automatically set to the unit that was entered (overriding the default from settings). This should be easily toggle-able when viewing the data without having to edit the data point. The tricky part here is that there are two different unit toggle for this screen (when not entering new data). The units to display, and the unit that is saved. You should be able to change the display unit without editing the data point, but you should also be able to go back and correct a data point where you accidentally selected the incorrect unit.

**Comment by cfilipov** [comment]
#36 addresses this.
