### ISSUE TITLE
Adding exercises

### ISSUE THREAD

**Issue by JonathanGuberman** [cfilipov/MuscleBook#24]
I noticed one of the [non-technical contributions](https://github.com/cfilipov/MuscleBook/blob/master/CONTRIBUTING.md#non-technical-contributions) is "Exercises," and I also noticed that several exercises that I do (weightlifting-related stuff: power cleans, hang cleans, etc.) aren't present in the list. I'm happy to help add these (I assume that [muscle data from ExRx](http://exrx.net/Lists/OlympicWeightlifting.html) is acceptable), but after looking through the code I couldn't find where the exercise list is coming from. Is this something I could help with?

**Comment by cfilipov** [comment]
Indeed!

I pulled the exercises from several sources, one of which is exrx. I don't know how I somehow missed these particular ones. Right now there is no nice way to add exercises. I intentionally held back on implementing an exercise editor in the app because of a technical issue with having globally unique primary keys. Right now the only way to add an exercise is to do it manually in the database. You can A) insert the rows manually using SQL on the SQLite3 file or B) Use a tool like [sqlitebrowser](http://sqlitebrowser.org/) to enter rows using the GUI, kinda of like excel.

Let me know your comfort level with either of these.

**Comment by JonathanGuberman** [comment]
I'm comfortable with SQL, but I haven't used SQLite specifically. Seems straightforward enough.

It looks like the exercise itself needs to be added to the exercise table, and the muscle groups used need to be added to the muscle_movement table. Do the exercises also need to be manually added to the various exercise_search_\* tables, or does that happen automatically? I don't see any triggers set up, so I'm guessing manually? But maybe I'm missing something.

I'm guessing that you didn't input all 1128 of the exercises manually; if you wrote a script to parse ExRx pages, I'd be happy to use that rather than write my own. 😀 

Are the gif, instructions, and/or link fields exposed anywhere in the UI, or are they for future expansion?

**Comment by cfilipov** [comment]
Ah, I forgot about search.. yeah. Bear with me here, this is going to be a long comment.

As you said, adding an exercise involves inserting a row into the `exercise` table, inserting a row into `exercise_search` and inserting rows into `muscle_movement` for each muscle the exercise involves. I don't know if it's SQLite itself or the wrapper I'm using (SQLite.swift) that does this, but I just insert into `exercise_search` and the rest of the `exercise_search_ *` tables are filled automatically. These steps are indeed done explicitly in the Swift code (see [DB.swift](https://github.com/cfilipov/MuscleBook/blob/0f596c542889dba3a696fcf7b0efcd14301e5f56/MuscleBook/DB.swift)). 

It's been a long time since I've done any database stuff myself, and even then I had a dba to stop me from doing anything stupid, so I fully expect there are things I did in this schema that will make my dba friends shake their heads at me in shame. If you think putting a trigger in place to automatically fill the search table makes sense, then I'm fine with that and would gladly pull in that change (it would make the code swift simpler too!). However, _I want to keep all schema-related stuff in SQLite.swift_, the reason for this is that any breaking changes to the schema will cause the code to not compile, this has been very very valuable so far (and also sometimes limiting to fight with doing things in SQLite.swift). 

Now back to the topic of adding exercises (you can skip ahead to the "going forward" part if you are not interested in the history):

I did indeed write a few scripts to pull these exercises and massage and clean up the data. It was a very labor-intensive process, and partially manual. Basically the process went like this:
1. I scraped the data into JSON using a modified python scraper for exrx I found on github (I'll have to wait until I get home to let you know the repo)
2. The resulting JSON data was the raw, but structured dump from exrx, complete with some duplicates and fields that were meant to be displayed, not used as data. 
3. Several scripts to clean up the data. Remove parenthetical notes, normalize muscle names, exercise names, remove non-printable characters that somehow made it in. Lots of stuff, I don't remember all of it but it's in the script.. somewhere..
4. Loaded the db directly in a Python and the JSON data and queried to make sure each muscle string perfectly matched the muscle names from the FMA data set.
5. Search & replace in the JSON file to fix any one-off things that would take longer to do in python.
6. Repeat steps 3-5 a bunch of times ad I found more issues.
7. Finally, translate the JSON into YAML. I had already written an YAML importer which automatically inserted the exercise and muscle data based on the muscle names. At this point in time there was no search functionality.
8. Of course, this didn't go perfectly, so manually fixed a few things after import.
9. Eventually I decided search was needed and added that capability, I wrote some one-off swift code that inserted all the data to the search table. This was before I figured out my schema migration strategy and before I released the source, so you wont see this in the initial commit.

It was a long and painful process. And while I still have the python scripts, YAML and JSON files for this, as you can imagine, they might not be extremely useful because of all the changes to the schema and even exercise data itself since I started. The YAML import code was literally just some one-off block of code at the startup of the app that read in YAML from a local file and did the inserts. This all sounds crazy, but I was the only one using this so I didn't mind, it was the path of least resistance.

My plan was to eventually move away form having all this data simply being seeded into the db. The idea was that you would install the app and the DB would be empty (either it gets created along with all the tables and all at first launch, or the db would come with the initial schema already setup, but completely empty of data). On first launch the app would find the exercises.yaml file and insert all that stuff into the corresponding tables. Exercises would be added by people sending pull requests modifying the YAML file to add exercises or correct/remove existing ones. Then on subsequent launches I would somehow determine that there is a new exercises file and update the DB. that last part is hard.

The problem all comes down to the fact that there is no canonical identifier for exercise data in this world. I lucked out with the [FMA](http://sig.biostr.washington.edu/projects/fm/AboutFM.html), it gave me a great (free) data set, and even better, a set of integers I could use as natural keys! 

Going forward:

Here's what I'm thinking: I can generate an updated YAML file from the current exercise/muscle data and make a new repo just for that file. One additional field would be a randomly-generated 64-bit int (or even a GUID) for each exercise. This will become the canonical exercise ID. This `exercises.yaml` file can be versioned in the same way I currently version the db schema. So it would be called `exercises-20160410215418161.yaml` (using the same format as [SQLiteMigrationManager](https://github.com/garriguv/SQLiteMigrationManager.swift)). On each app launch, it checks the app bundle to see if there is an updated exercises manifest, if there is, it updates the table contents from this file. If the canonical ID is just randomly-generated Int64, then this can also be used as the primary key, which means the workout data will stay consistent even if the exercise table is dropped and re-imported (what are the perf implications of using a non-incrementing primary key?).

**Comment by cfilipov** [comment]
By the way, the gif and instructions fields you asked about were indeed added for future expansion. it just so happens that I finally implemented those last week. I just haven't pushed those commits yet. When I get home tonight I'll push that code.

**Comment by cfilipov** [comment]
Have a look at the [exercise yaml format spec](https://github.com/cfilipov/MuscleBook/blob/b0d7504cd763b07913b83ef103e3cbf53092e4cb/ExerciseYAMLFormat.md). If you can get the exercise data into this format, I can get it imported. I also added the ability to expert the existing exercise data as yams to get an idea of what it looks like.

One thing I haven't settled on yet is the identifier. I'm tempted to keep the identifiers as-is since they have been in use already, and reserve random IDs > 10000 for exercises added in-app. Any thoughts?

**Comment by cfilipov** [comment]
[Here's the script I used](https://github.com/cfilipov/exercise_scraper) to pull all the data. I forked the original because it was not actually crawling all the pages, and it wasn't getting all the data I wanted. In addition to that script, I also used the shell script from [this repo](https://github.com/wsouto/excraper) to mirror the website locally so I didn't hammer them with requests while debugging the script. I suggest the same if you intend to use it. Like I said earlier though, it was a rough process so I don't know how much help this will be. I also have the scripts I used to post-process this JSON somewhere. I'll share them when I find them.

**Comment by JonathanGuberman** [comment]
Wow, lots of information to read through! Here are my thoughts:

> I don't know if it's SQLite itself or the wrapper I'm using (SQLite.swift) that does this, but I just insert into exercise_search and the rest of the exercise_search_ \* tables are filled automatically. These steps are indeed done explicitly in the Swift code (see DB.swift) ... If you think putting a trigger in place to automatically fill the search table makes sense, then I'm fine with that and would gladly pull in that change

If this is the way that the library is doing it, then there's probably a reason for it and I don't know enough about Swift and SQLite to argue that it should change. I'm used to dealing with Python and MySQL/Postgres, and I wouldn't bother having an `exercise_search` table at all, I'd just use the same data from the `exercise` table, but, at least for the time being, I think leaving well enough alone is probably the best course of action.

> One thing I haven't settled on yet is the identifier. I'm tempted to keep the identifiers as-is since they have been in use already, and reserve random IDs > 10000 for exercises added in-app. Any thoughts?

I think this sound sensible. No need for large random IDs for the built-in exercises (although, to answer your question, I think the performance implications on a DB of this size would be negligible).

> Have a look at the exercise yaml format spec. If you can get the exercise data into this format, I can get it imported. I also added the ability to expert the existing exercise data as yams to get an idea of what it looks like.

This seems like the best way to go. I'll work on getting the data into that format, one way or another. If I can't get it done in the next couple of days it probably won't happen for another week, though, because I'm going to be travelling and won't have time for it.

**Comment by cfilipov** [comment]
The `exercise_search` table is a side effect of using SQLite's [full text search module](http://www.sqlite.org/fts3.html). It does a really good job at search, pretty efficiently, and it seems this is a requirement to get FTS.

Thanks for looking into more exercises. No rush on getting that data. I still need to implement the import part of this process, which shouldn't actually take too long, but there's a lot to do and only few hours a day to do it.

**Comment by JonathanGuberman** [comment]
I found why the scraper didn't get the Olympic lifts: that section of the directory doesn't match the regex from the scraper. I found five sections that weren't picked up, all from the "Other Exercises" section in the bottom right of the [main directory](http://exrx.net/Lists/Directory.html):
- [Olympic-style Weightlifts](http://exrx.net/Lists/OlympicWeightlifting.html)
- [Plyometrics](http://exrx.net/Lists/PowerExercises.html)
- [Cardio](http://exrx.net/Lists/CardioExercises.html)
- [Kettlebell](http://exrx.net/Lists/KettlebellExercises.html)
- [Miscellaneous](http://exrx.net/Lists/OtherExercises.html)

Putting aside for a moment which of those sections we'd want to include, they all seem to have one thing in common: instead of a "Muscles" section they have a "Force (Articulation)" section. This has subsections such as "Dynamic," "Dynamic (Passive)," and "Static," (there may be others on exercises that I haven't seen) which in turn contain a joint and an [articulation](http://exrx.net/Lists/Articulations.html) (e.g. [Hip - Extension](http://exrx.net/Articulations/Hip.html#Extension)). Each of these lists several muscle groups involved in that articulation. See the [kettlebell two arm swing](http://exrx.net/WeightExercises/Kettlebell/KBTwoArmSwing.html) for a representative example.

I'm not sure what we would want to do with this. Just map the articulations to muscles directly and cut out that force/articulation data? Add force/articulation data in? Ignore these exercises entirely?

**Comment by cfilipov** [comment]
At some point I did want to include articulation semantics into the muscle//exercise data model (it's very useful info!), but I don't see myself working on that in the near future. My philosophy when scraping data is to grab as much as possible. It doesn't hurt to put all of it into a model then strip it out later vs not take it in and then later regret it when it's harder to augment. 

The big question now is: does the concept of target muscle even apply to these exercises? I think so, you would still list out some muscles that were targeted by these workouts, so they should be included, though it looks like it would have to be done manually because exrx does not include it. This way, the anatomy diagram can highlight the muscles effected when you do these exercises. One option might be to copy the muscle classifications from compound exercises that have similar movements.

This also brings up the idea that maybe I should also include an "author notes" field in the exercise data where one can note that they guessed at certain data in the exercise. This would be really useful for when someone wants to go in a cleanup/verify some data is correct.

**Comment by JonathanGuberman** [comment]
I actually used the app for the first time during my workout today, and noticed some more issues with the exercise data from ExRx: because of the way they organize the exercises, each exercise seems to have just one target muscle, but some exercises are listed identically or nearly identically under multiple muscles. See, for example, the deadlift ([erector spinae](http://exrx.net/WeightExercises/ErectorSpinae/BBDeadlift.html) and ([gluteus maximus](http://exrx.net/WeightExercises/GluteusMaximus/BBDeadlift.html)) and the squat ([quadriceps](http://exrx.net/WeightExercises/Quadriceps/BBSquat.html) and [gluteus maximus](http://exrx.net/WeightExercises/GluteusMaximus/BBSquat.html)). In the case of the squat they seem to be differentiating between high bar and low bar, but if that's the case the names are a little misleading.

I thought it was very strange to only have the erector spinae light up on the muscle diagram after my deadlifts!

**Comment by cfilipov** [comment]
I noticed this as well, it's very frustrating how unstructured their data is. Unfortunately there doesn't seem to be a nice automated way to fix this. The MB data model supports multiple target muscles, of course, so I think the solution would be to manually fix this when I get the YAML export/import working.

It shouldn't actually be that hard, even though there are 1,100+ exercises, I only do about 20 of them. And I imagine most exercises do actually have just one target muscle, so it would only be the big compound exercises that need to be edited.

**Comment by cfilipov** [comment]
I got a patch ready for the exercise import stuff (and a few other open issues). I actually had this done a couple weeks ago but I've been sitting on it to test out the app (also laziness/being busy with work and home stuff). I'll push it when I get home today.

**Comment by cfilipov** [comment]
You can now add exercises in [v0.1.0](https://github.com/cfilipov/MuscleBook/releases/tag/v0.1.0) by editing the YAML file. Send me a pull request with the changes. If you are adding a new exercise, make sure the increment the exercise ID by 1.
