### ISSUE TITLE
Storing individual sets. 

### ISSUE THREAD

**Issue by cfedk** [cfilipov/MuscleBook#28]
At the moment, all I can add for one exercise per workset is reps x weight. 

Sets have different weights. So I expect to be able to add

Barbell Bench Press 

> Set: 5x50
> Set: 5x60
> Set 5x70...

**Comment by JonathanGuberman** [comment]
I believe that the idea is that each data point is a set. So, in your example, you would add each set separately. This has the advantages: for example, marking a set as "warmup" or "failure," which only applies to individual sets. It also lets you record the start time of each individual set. This is useful for tracking recovery (e.g. "ah, I see that when I rested for 2 minutes between sets I was able to get 2 more reps on my final set to failure").

**Comment by cfedk** [comment]
That's fair. If it is by design rather than omission, I'm all for it!

**Comment by cfilipov** [comment]
Yeah, as @JonathanGuberman said, it was by design. I've heard this request before, and I hope it's something that people can grow accustomed to after using it because entering sets individually has some really nice advantages in terms of the data stored on each set. I would be open to re-evaluating this in the future if it can be demonstrated to be a very important omission, but logging sets individually was one of the central design choices in MB (both in terms us user-facing stuff and architecture of the db/code) so it won't be too easy to change.

**Comment by cfedk** [comment]
The more I thought about it, the more I agree. 

Teach me to file before thinking for myself.
