### ISSUE TITLE
[Bug] App crashes on open

### ISSUE THREAD

**Issue by JonathanGuberman** [cfilipov/MuscleBook#34]
I've been using the app for the past week while on my vacation, and (with minor exceptions) it's worked great, save for some issues/enhancements already documented here. However, when I went to open the app today, it crashed immediately on startup. It still appears in the application switcher, but switching to it also crashes, after showing the app screen briefly. The app is unresponsive during that brief time. Neither force quitting from the app switcher nor restarting the phone helps, so at this point I'm completely unable to access the app. 

I'm on an iPhone 5. Let me know what else I can do to help debug.

**Comment by JonathanGuberman** [comment]
This may actually be an issue on my end with an expired self-signed certificate (although I'm surprised it crashes without any notice if that's the case, but I don't have any experience with side-loading so maybe that's just what happens). I'll look into a bit more and see what I can figure out.

**Comment by cfilipov** [comment]
Before trying to debug anything, make sure to backup your data. Plug in your iPhone, open iTunes, select the app and scroll down and you should see a section for the app's documents. There should be just one file, the database. Download that.

You can do the reverse (drop in a database file to replace an existing one) if you delete the app and re-install it to use the backed up database.

Now that you have a backup:

I can't do much without seeing crash logs (maybe I shouldn't have removed the Crashlytics lib huh?). Please send me the crash logs and console output. You can get crash logs through xcode or even on the device, you can get the console output via xcode. See these [instructions](https://developer.apple.com/library/ios/qa/qa1747/_index.html) for how to get them.

That said, I suspect you are correct that this is an issue with an expired provisioning profile. iOS will often warn you via alert dialog to tell you that a profile is expiring, but not always. Having the app launch and then immediately exit is a common sign that the binary is being killed due to invalid code signing (read: expired cert or profile). If that's the case you won't have a crash log (I think). You can verify that the provisioning profile is expired by going to the system settings on iOS. It's under General -> Profiles & Device Management. Fixing provisioning issues can be pretty involved and it depends on if you have a dev account and generated certs and profile manually or if you let xcode do it for you. 

The good news is that the next version of xcode that's coming soon makes provisioning much easier.

**Comment by JonathanGuberman** [comment]
It was indeed a provisioning problem. I had let Xcode do it for me, and I guess it expires quickly. Simply building again fixed it, although it'd be nice to get a more permanent solution.

I did backup the data, but it wasn't necessary; after reinstalling from Xcode the data was all still there, so that's nice! Thanks for the tips.

**Comment by cfilipov** [comment]
I have some good news about a more permanent solution. I originally had no plans to have this on the app store, but things changed and it looks like I will be able to distribute it there after all. However, I plan to make it a paid app (~$10 or more). I will continue to update this repo so that anyone who doesn't want to pay can just build it themselves, that will be the trade off. This is way off into the future when the app is more stable, so I don't know when that would be.

**Comment by JonathanGuberman** [comment]
I'm very happy to hear that! Does that mean that #1 has been resolved?

I showed the app to the trainer I was working with, and he keeps asking me when he'll be able to download it! Now I can tell him "eventually" rather than "maybe never"! 😀

**Comment by cfilipov** [comment]
Not really. I think it's OK to use the artwork (I'm already redistributing it on GitHub after all), but I'd rather have it more clearly defined. If it becomes an issue (ie. the original artist sends a takedown request) then I will hopefully have enough funds from App Store sales to commission an original work or buy it form the artist. If there aren't enough App Store sales to pay for new artwork, then it probably wasn't worth having it up there in the first place.
