### ISSUE TITLE
[Bug] Recalculating workout error when saving first set

### ISSUE THREAD

**Issue by JonathanGuberman** [cfilipov/MuscleBook#43]
After my first warmup set of the day, I tried saving and received a "recalculating workout error" (or something like that, sorry, didn't get a screenshot). Turning off the warmup flag allowed me to save it. Tried another warmup set and it saved fine; tried to edit the original one to add the flag and had the error again. Did some more sets, tried to edit the original again, and this time it worked.

**Comment by cfilipov** [comment]
I ran into this very same bug the other day. This was introduced in 0.1.0 when I fixed the issue with filtering out warmup sets from the intensity calculation. The fix is pretty simple, I'll fix it and likely push an update this weekend. Until then you will have to use the workaround you discovered.

**Comment by cfilipov** [comment]
Fixed in v0.1.1
